[build]
  command = "rustup toolchain install stable && rustup default stable && rustup target add wasm32-unknown-unknown && cargo install trunk && cargo run --bin gen_posts && trunk build --release"
  publish = "dist"